config/routes.rb
Rails.application.routes.draw do
# resources :restaurants

root 'welcome_pages#start'

get 'restaurants/index', to: 'restaurants#index', as: :restaurants
get 'restaurants/new', to: 'restaurants#new', as: :new_restaurant
post 'restaurants/index', to: 'restaurants#create', as: :create_restaurant
get 'restaurants/:location/edit', to: 'restaurants#edit', as: :edit_restaurant
patch 'restaurants/:location', to: 'restaurants#save', as: :save_restaurant
get 'restaurants/:location', to: 'restaurants#show', as: :restaurant

# add update and destroy
get 'menu/items', to: 'menu_items#index', as: :menu_items
post 'menu/items', to: 'menu_items#create', as: :create_menu_item
get 'menu/items/add', to: 'menu_items#new', as: :new_menu_item
get 'menu/items/:id/edit', to: "menu_items#edit", as: :edit_menu_item
get 'menu/:location/index', to: 'menu_items#show_location', as: :menu
patch 'menu/items/:id', to: 'menu_items#save', as: :save_item
get 'menu/items/:id', to: 'menu_items#show_one', as: :menu_item  #done

get 'login/new', to: 'session#new', as: :login
post 'login/create', to: 'session#create', as: :create_session
get 'logout', to: 'session#destroy', as: :logout
get 'users/index', to: 'users#index', as: :users
post 'users/index', to: 'users#create', as: :create_user
get 'users/new', to: 'users#new', as: :new_user
get 'users/:id/edit', to: 'users#edit', as: :edit_user
get 'users/:id', to: 'users#show', as: :user
patch 'users/:id', to: 'users#save', as: :save_user

post 'order/add', to: 'orders#add', as: :add_to_order
get 'order', to: 'orders#view', as: :view_order
post 'order', to: 'orders#submit', as: :submit_order
get 'order/complete', to: 'orders#complete', as: :complete_order

get 'start', to: 'welcome_pages#start', as: :start


end

app/models/menu_item.rb
class MenuItem
    include Mongoid::Document
    field :item, type: String
    field :price, type: Float
    # field :add_on_price, type: Float
    # field :add_on, type: Boolean
    field :category, type: String
    field :description, type: String
    field :photo, type: String
    has_and_belongs_to_many :restaurants, autosave: true

    def get_locations
        self.restaurants.collect {|r| r.city}
    end

end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController

    def index
        @menu_items = MenuItem.all
    end

    def new
        @menu_item = MenuItem.new
        # CHANGE TO ATTACH TO RESTAURANT
    end

    def create
        @menu_item = MenuItem.new(menu_item_params)
        if @menu_item.save
            redirect_to action: 'index', notice: 'Item successfully added.'

        else
            render action: 'new', alert: 'failed to add.'
        end 
    end

    def show_location
        @restaurant = Restaurant.where(:'city' => params[:location]).first
    end

    def show_one
        # restaurant = Restaurant.where(:'city' => params[:location]).first
        @menu_item = MenuItem.find(params[:id])
    end

    def edit
        # @restaurant = Restaurant.where(:'city' => params[:location]).first
        @menu_item = MenuItem.find(params[:id])
    end

    def save
        @menu_item = MenuItem.find(params[:id])
        if @menu_item.update(menu_item_params)
            redirect_to menu_items_path, notice: 'item updated'
        else
            render action: 'edit', alert: 'try again.'
        end
    end

    private

        def menu_item_params
            params.require(:menu_item).permit(:item, :price, :category, :description, :restaurant_ids => [])
        end

end

app/views/menu_items/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2" style='background-color:white;opacity:.7'>
      <div class="form-horizontal">
      <%= form_for(@menu_item, class: 'form') do |f| %>
        <div class='field form-group'>
          <%= f.label(:item, "Item name") %>
           <div class="col-sm-12">
          <%= f.text_field(:item) %>
          </div>
        </div>
        <div class='field form-group'>
          <%= f.label(:price, "Price") %>
          <div class="col-sm-12">
          <%= f.number_field(:price, :class => 'text_field', :step => 0.01) %>
          </div>
        </div>
        <div class='field form-group'>
          <%= f.label(:category, "Category")%>
          <div class="col-sm-12">
          <%= f.text_field(:category)%>
          </div>
        </div>
        <div class='field form-group'>
          <%= f.label(:description, "Description") %>
          <div class="col-sm-12">
          <%= f.text_field(:description) %>
          </div>
        </div>
        <div class='field form-group'>
          <%= f.label(:restaurant_ids, "Locations") %>
          <div class="col-sm-12">
          <%= f.collection_select(:restaurant_ids, Restaurant.all, :id, :city, {}, {multiple: true}) %>
          </div>
        </div>


        <div class='actions'>
          <%= f.submit%>
        </div>
      <%end%>
      </div>
    </div>
  </div>
</div>

app/views/menu_items/edit.html.erb
<%= render 'form' %>

app/views/menu_items/index.html.erb
<br>

<div class="container">
<div class="row">
  <div class="col-md-10 col-md-offset-1" style="background-color:white;opacity:.7">
    <table class="table table-bordered table-hover table-responsive">
    <tr>
    <th>Item</th>
    <th>Category</tjh>
    <th>Price</th>
    <th>Description</th>
    <th>Locations</th>

    <th></th>
    <tr>
    <%@menu_items.each do |m|%>
    <tr>
    <td><%=m.item%></td>
    <td><%=m.category%></td>
    <td><%=m.price%></td>
    <td><%=m.description%></td>
    <td><%=m.get_locations.join(', ')%></td>
    <!-- <td><%=link_to 'more', menu_item_path(:id => m.id)%></td> -->
    <td><%=link_to 'edit', edit_menu_item_path(:id => m.id)%></td>
    </tr>
    <%end%>
    </table>
  </div>
</div>
</div>

app/views/menu_items/new.html.erb
<h2>menu#new</h2>
<h2>add new menu item</h2>

<%= render 'form' %>

<%= link_to :back%>

app/views/menu_items/show_location.html.erb
<!-- Page Content -->
<div class="container">

  <div class="row">

<!-- left side column for totals -->
    <div class="col-md-2">
      <p class="lead col-sm-2"><img src=''></p>

<!--         <div style='background-color: white'>
          <table>
          <%@restaurant.menu_items.each do |m|%>
          <tr>
          <td><%= m.item %></td>
          <td><%= m.price %></td>
          </tr>
          <%end%>
          </table>
        </div> -->
    </div>

<!-- menu column -->
    <div class="col-md-9" style='opacity:0.9'>

      <div class="thumbnail">
        <img class="img-responsive" src="/assets/food/B2CqpT2CMAEb8SX.jpg" alt="http://placehold.it/800x300">

        <!-- text left -->
        <div class="caption-full col-md-7 col-md-offset-1">

          <h4><a href="#">HEADING</a></h4>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
          <hr>
        </div>
      </div>

      <div class="well">
        <%@restaurant.menu_items.each do |m|%>
        <div class="row">
          <div class='col-md-5 col-md-offset-1'>
            <%= m.item %>
            <%= m.category %>
            <%= m.description %>
          </div>
          <div class='col-md-1 col-md-offset-3'>
            <%= number_to_currency(m.price) %>
          </div>
        </div>

        <div class='row'>
          <div class='col-md-4 col-md-offset-9'>  
            <%if !current_user.nil? %>
              <%= form_tag(add_to_order_path, method: "post") do %>
                <%= number_field_tag(:quantity, 1, min: 1, max: 20, class: 'col-sm-4 form_control') %>
                <%= hidden_field_tag(:restaurant_id, @restaurant.id) %>
                <%= hidden_field_tag(:item_id, m.id) %>
                <%= submit_tag("add", class: 'btn btn-default', style:'background-color:#fe6c33') %>
            <%end%> 

          <%end%>
        </div>
      </div>
      <hr>
        <%end%>

        <div class="row">
          <div class="col-md-12">
          </div>
        </div>
        <hr>

      </div>
    </div>
  </div>
</div>
<!-- /.container -->

<div class="container">

  <hr>


<div>
<%=link_to 'Complete Order', view_order_path%>
</div>
<div>
<%=link_to 'All locations', restaurants_path%>
</div>
<div>
<%=link_to 'Restaurant Main', restaurant_path(:location => @restaurant.city)%>
</div>

app/views/menu_items/show_one.html.erb
<h2>menu_items#show_one</h2>
<h2>Single Menu Item</h2>
<div>
<div><%=@menu_item.item%></div>
<div><%=@menu_item.price%></div>
<div><%=@menu_item.category%></div>
<div><%=@menu_item.description%></div>
<div><%=@menu_item.get_locations.join(', ')%></div>
<div>PHOTO THUMBNAIL</div>
</div>
<div>
<%=link_to 'edit', edit_menu_item_path%>
</div>