config/routes.rb
Rails.application.routes.draw do
# resources :restaurants

root 'welcome_pages#start'

get 'restaurants/index', to: 'restaurants#index', as: :restaurants
get 'restaurants/new', to: 'restaurants#new', as: :new_restaurant
post 'restaurants/index', to: 'restaurants#create', as: :create_restaurant
get 'restaurants/:location/edit', to: 'restaurants#edit', as: :edit_restaurant
patch 'restaurants/:location', to: 'restaurants#save', as: :save_restaurant
get 'restaurants/:location', to: 'restaurants#show', as: :restaurant

# add update and destroy
get 'menu/items', to: 'menu_items#index', as: :menu_items
post 'menu/items', to: 'menu_items#create', as: :create_menu_item
get 'menu/items/add', to: 'menu_items#new', as: :new_menu_item
get 'menu/items/:id/edit', to: "menu_items#edit", as: :edit_menu_item
get 'menu/:location/index', to: 'menu_items#show_location', as: :menu
patch 'menu/items/:id', to: 'menu_items#save', as: :save_item
get 'menu/items/:id', to: 'menu_items#show_one', as: :menu_item  #done

get 'login/new', to: 'session#new', as: :login
post 'login/create', to: 'session#create', as: :create_session
get 'logout', to: 'session#destroy', as: :logout
get 'users/index', to: 'users#index', as: :users
post 'users/index', to: 'users#create', as: :create_user
get 'users/new', to: 'users#new', as: :new_user
get 'users/:id/edit', to: 'users#edit', as: :edit_user
get 'users/:id', to: 'users#show', as: :user
patch 'users/:id', to: 'users#save', as: :save_user

post 'order/add', to: 'orders#add', as: :add_to_order
get 'order', to: 'orders#view', as: :view_order
post 'order', to: 'orders#submit', as: :submit_order
get 'order/complete', to: 'orders#complete', as: :complete_order

get 'start', to: 'welcome_pages#start', as: :start


end

app/models/restaurant.rb
class Restaurant
    include Mongoid::Document
    field :name, type: String
    field :address, type: String
    field :city, type: String
    field :state, type: String
    field :zip, type: String
    field :phone, type: String
    field :email, type: String
    has_and_belongs_to_many :menu_items, autosave: true
    has_many :orders, autosave: true

    def remove_menu_item(item)
        self.menu_items.delete(item)
        self.save!
    end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

    def index
        @restaurants = Restaurant.all
    end

    def show
        @restaurant = Restaurant.where(:'city' => params[:location]).first
    end

    def new
        @restaurant = Restaurant.new
    end

    def edit
        @restaurant = Restaurant.where(:'city' => params[:location]).first
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)
        if @restaurant.save
            redirect_to restaurants_path, notice: "successfully added"
        else
            render action: 'new', alert: 'Location failed to save.'
        end
    end

    def save
        @restaurant = Restaurant.where(:'city' => params[:location]).first
        puts restaurant_params
        if @restaurant.update(restaurant_params)
            redirect_to restaurant_path(:location => params[:location])
        else
            render action: 'edit', alert: 'Changes failed to save.'
        end
    end

    def destroy
    end

    private

        def restaurant_params
            params.require(:restaurant)
            .permit(:name, :address, :city, :state, :zip, :phone, :email, :menu_item_ids => [])
        end

end

app/views/restaurants/edit.html.erb
<h2>restaurants#edit</h2>


<div class="container">
  <div class="row">
    <div class="col-lg-4 col-lg-offset-2" style='background-color:white;opacity:.7'>
      <div class="form-horizontal">
        <%= form_for(@restaurant, url: save_restaurant_path(location: @restaurant.city), method: :patch) do |f| %>
          <% if @restaurant.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this user from being saved:</h2>
              <ul>
              <% @restaurant.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= f.label(:name, 'Restaurant Name') %><br>
            <%= f.text_field(:name) %>
          </div>
          <div class="field">
            <%= f.label(:address, 'Address') %><br>
            <%= f.text_field(:address) %>
          </div>
          <div class="field">
            <%= f.label(:email, 'E-mail address')  %><br>
            <%= f.email_field(:email) %>
          </div>
          <div class="phone">
            <%= f.label(:phone, 'Phone number') %><br>
            <%= f.phone_field(:phone) %>
          </div>
          <div class="field">
            <%= f.label(:city, 'City') %><br>
            <%= f.text_field(:city) %>
          </div>
          <div class="field">
            <%= f.label(:state, 'State') %><br>
            <%= f.text_field(:state) %>
          </div>
          <div class="field">
            <%= f.label(:zip, 'Zip Code') %><br>
            <%= f.text_field(:zip) %>
          </div>
          <div class="field">
            <%= f.label(:menu_item_ids, 'Menu Items') %>
            <%= f.collection_select(:menu_item_ids, MenuItem.all, :id, :item, {}, {multiple: true}) %>
          </div>


          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 col-md-offset-1">
      <table class="table table-bordered" style='background-color:white;opacity:.7'>
      <thead>
        <tr>
         <th>Name</th>
         <th>City</th>
         <th></th>
         <th></th>
        </tr>
      </thead>

      <tbody>
      <%@restaurants.each do |r| %>
         <tr>
          <td><%=r.name%></td>
          <td><%=r.city%></td>
          <td><%= link_to 'more', restaurant_path(:location => r.city) %></td>
          <td><%= link_to 'edit', edit_restaurant_path(:location => r.city) %></td>
         </tr>
      <%end%>
      </tbody>
      </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-2 col-md-offset-9">
    <%= link_to 'New Location', new_restaurant_path %>
  </div>
</div>

app/views/restaurants/new.html.erb
<h2>restaurants#new</h2>

<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= f.label(:name, 'Restaurant Name', class: 'col-sm-2') %><br>
    <%= f.text_field(:name, class:'form-control') %>
  </div>
  <div class="field form-group">
    <%= f.label(:address, 'Address') %><br>
    <%= f.text_field(:address, class:'form-control') %>
  </div>
  <div class="field form-group">
    <%= f.label(:email, 'E-mail address')  %><br>
    <%= f.email_field(:email, class:'form-control') %>
  </div>
  <div class="phone form-group">
    <%= f.label(:phone, 'Phone number') %><br>
    <%= f.phone_field(:phone, class:'form-control') %>
  </div>
  <div class="field form-group">
    <%= f.label(:city, 'City') %><br>
    <%= f.text_field(:city, class:'form-control') %>
  </div>
  <div class="field form-group">
    <%= f.label(:state, 'State') %><br>
    <%= f.text_field(:state, class:'form-control') %>
  </div>
  <div class="field form-group">
    <%= f.label(:zip, 'Zip Code') %><br>
    <%= f.text_field(:zip, class:'form-control') %>
  </div>
  <div class="field form-group">
    <%= f.label(:menu_item_ids, 'Menu Items') %>
    <%= f.collection_select(:menu_item_ids, MenuItem.all, :id, :item, {}, {multiple: true}) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div class="container">
    <div class='jumbotron'>
        <h2><%=@restaurant.name%></h2>
        <p><%=@restaurant.address%></p>
        <p><%=@restaurant.city%>
        <%=@restaurant.state%>
        <%=@restaurant.zip%></p>
        <p><%=@restaurant.phone%></p>
        <p><%=@restaurant.email%></p>
        <%=link_to 'menu', menu_path%>
    </div>



    <div class="row">
        <div>
        <%=link_to "All locations", restaurants_path%>
        </div>
    </div>



</div>
</div>
</div>