config/routes.rb
Rails.application.routes.draw do
# resources :restaurants

root 'welcome_pages#start'

get 'restaurants/index', to: 'restaurants#index', as: :restaurants
get 'restaurants/new', to: 'restaurants#new', as: :new_restaurant
post 'restaurants/index', to: 'restaurants#create', as: :create_restaurant
get 'restaurants/:location/edit', to: 'restaurants#edit', as: :edit_restaurant
patch 'restaurants/:location', to: 'restaurants#save', as: :save_restaurant
get 'restaurants/:location', to: 'restaurants#show', as: :restaurant

# add update and destroy
get 'menu/items', to: 'menu_items#index', as: :menu_items
post 'menu/items', to: 'menu_items#create', as: :create_menu_item
get 'menu/items/add', to: 'menu_items#new', as: :new_menu_item
get 'menu/items/:id/edit', to: "menu_items#edit", as: :edit_menu_item
get 'menu/:location/index', to: 'menu_items#show_location', as: :menu
patch 'menu/items/:id', to: 'menu_items#save', as: :save_item
get 'menu/items/:id', to: 'menu_items#show_one', as: :menu_item  #done

get 'login/new', to: 'session#new', as: :login
post 'login/create', to: 'session#create', as: :create_session
get 'logout', to: 'session#destroy', as: :logout
get 'users/index', to: 'users#index', as: :users
post 'users/index', to: 'users#create', as: :create_user
get 'users/new', to: 'users#new', as: :new_user
get 'users/:id/edit', to: 'users#edit', as: :edit_user
get 'users/:id', to: 'users#show', as: :user
patch 'users/:id', to: 'users#save', as: :save_user

post 'order/add', to: 'orders#add', as: :add_to_order
get 'order', to: 'orders#view', as: :view_order
post 'order', to: 'orders#submit', as: :submit_order
get 'order/complete', to: 'orders#complete', as: :complete_order

get 'start', to: 'welcome_pages#start', as: :start


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_filter :authorize
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end
  helper_method :current_user

# protected

  def authorize
    # redirect_to login_url, alert: "Not authorized" if current_user.nil?
    redirect_to login_path, alert: "Not authorized" if !current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/views/application/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Order', restaurants_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Locations', restaurants_path, class: "navbar-brand" %>
        </li>
        <li>
          <a href="#">btn2</a>
        </li>
        <li>
          <a href="#">btn3</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user.nil? %>
          <li>
            <%= link_to 'logout', logout_path %>
          </li>
        <% else %>
          <li>
            <%= link_to 'create account', new_user_path %>
          </li>
          <li>
            <%= link_to 'login', login_path %>
          </li>        
        <%end%>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>